"""core_schema

Revision ID: bd2afd21a840
Revises: f6a0d1cdb248
Create Date: 2026-03-09 16:25:54.080898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd2afd21a840"
down_revision: Union[str, None] = "f6a0d1cdb248"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "empresas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("razon_social", sa.String(length=255), nullable=False),
        sa.Column("cuit", sa.String(length=11), nullable=False),
        sa.Column("condicion_iva", sa.String(length=50), nullable=False),
        sa.Column("domicilio", sa.String(length=255), nullable=False),
        sa.Column("localidad", sa.String(length=100), nullable=False),
        sa.Column("provincia", sa.String(length=100), nullable=False),
        sa.Column("codigo_postal", sa.String(length=10), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=50), nullable=True),
        sa.Column("inicio_actividades", sa.Date(), nullable=False),
        sa.Column("logo", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_empresas_cuit"), "empresas", ["cuit"], unique=True)
    op.create_index(op.f("ix_empresas_id"), "empresas", ["id"], unique=False)
    op.create_table(
        "certificados",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("cuit", sa.String(length=11), nullable=False),
        sa.Column("fecha_emision", sa.Date(), nullable=False),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=False),
        sa.Column("archivo_crt", sa.String(length=255), nullable=False),
        sa.Column("archivo_key", sa.String(length=255), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("ambiente", sa.String(length=20), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_certificados_id"), "certificados", ["id"], unique=False)
    op.create_table(
        "clientes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("razon_social", sa.String(length=255), nullable=False),
        sa.Column("tipo_documento", sa.String(length=20), nullable=False),
        sa.Column("numero_documento", sa.String(length=20), nullable=False),
        sa.Column("condicion_iva", sa.String(length=50), nullable=False),
        sa.Column("domicilio", sa.String(length=255), nullable=True),
        sa.Column("localidad", sa.String(length=100), nullable=True),
        sa.Column("provincia", sa.String(length=100), nullable=True),
        sa.Column("codigo_postal", sa.String(length=10), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=50), nullable=True),
        sa.Column("notas", sa.String(length=500), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_clientes_empresa_activo", "clientes", ["empresa_id", "activo"], unique=False
    )
    op.create_index(op.f("ix_clientes_id"), "clientes", ["id"], unique=False)
    op.create_index(
        "ix_clientes_razon_social", "clientes", ["razon_social"], unique=False
    )
    op.create_index(
        "ix_clientes_tipo_numero_doc",
        "clientes",
        ["tipo_documento", "numero_documento"],
        unique=False,
    )
    op.create_table(
        "puntos_venta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_puntos_venta_id"), "puntos_venta", ["id"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("es_admin", sa.Boolean(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("ultimo_login", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_index(op.f("ix_usuarios_id"), "usuarios", ["id"], unique=False)
    op.create_table(
        "comprobantes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo_comprobante", sa.Integer(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("fecha_emision", sa.Date(), nullable=False),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("descuento", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("iva_21", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("iva_10_5", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("iva_27", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("otros_impuestos", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cae", sa.String(length=14), nullable=True),
        sa.Column("cae_vencimiento", sa.Date(), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("cotizacion", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("observaciones", sa.String(length=500), nullable=True),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("punto_venta_id", sa.Integer(), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["cliente_id"], ["clientes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["punto_venta_id"], ["puntos_venta.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "empresa_id",
            "punto_venta_id",
            "tipo_comprobante",
            "numero",
            name="uq_comprobantes_empresa_pv_tipo_numero",
        ),
    )
    op.create_index("ix_comprobantes_cae", "comprobantes", ["cae"], unique=False)
    op.create_index(
        "ix_comprobantes_empresa_fecha",
        "comprobantes",
        ["empresa_id", "fecha_emision"],
        unique=False,
    )
    op.create_index("ix_comprobantes_estado", "comprobantes", ["estado"], unique=False)
    op.create_index(
        "ix_comprobantes_fecha_emision", "comprobantes", ["fecha_emision"], unique=False
    )
    op.create_index(op.f("ix_comprobantes_id"), "comprobantes", ["id"], unique=False)
    op.create_index(
        "ix_comprobantes_tipo_numero",
        "comprobantes",
        ["tipo_comprobante", "numero"],
        unique=False,
    )
    op.create_table(
        "lotes_comprobantes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre_archivo", sa.String(length=255), nullable=False),
        sa.Column("archivo_hash", sa.String(length=64), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("modo_procesamiento", sa.String(length=20), nullable=False),
        sa.Column("procesamiento_async", sa.Boolean(), nullable=False),
        sa.Column("total_filas", sa.Integer(), nullable=False),
        sa.Column("total_grupos", sa.Integer(), nullable=False),
        sa.Column("grupos_validos", sa.Integer(), nullable=False),
        sa.Column("grupos_con_error", sa.Integer(), nullable=False),
        sa.Column("grupos_emitidos", sa.Integer(), nullable=False),
        sa.Column("grupos_fallidos", sa.Integer(), nullable=False),
        sa.Column("mensaje_resumen", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "empresa_id",
            "archivo_hash",
            name="uq_lotes_comprobantes_empresa_hash",
        ),
    )
    op.create_index(
        "ix_lotes_comprobantes_empresa_estado",
        "lotes_comprobantes",
        ["empresa_id", "estado"],
        unique=False,
    )
    op.create_index(
        "ix_lotes_comprobantes_hash",
        "lotes_comprobantes",
        ["empresa_id", "archivo_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lotes_comprobantes_id"), "lotes_comprobantes", ["id"], unique=False
    )
    op.create_table(
        "comprobante_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=True),
        sa.Column("descripcion", sa.String(length=500), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("unidad", sa.String(length=50), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "descuento_porcentaje", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("iva_porcentaje", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("comprobante_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comprobante_id"], ["comprobantes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comprobante_items_id"), "comprobante_items", ["id"], unique=False
    )
    op.create_table(
        "lotes_comprobantes_grupos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comprobante_ref", sa.String(length=100), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("tipo_comprobante", sa.Integer(), nullable=True),
        sa.Column("punto_venta_numero", sa.Integer(), nullable=True),
        sa.Column("cliente_documento", sa.String(length=20), nullable=True),
        sa.Column("cliente_razon_social", sa.String(length=255), nullable=True),
        sa.Column("total_estimado", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.Column("mensajes_json", sa.JSON(), nullable=True),
        sa.Column("cae", sa.String(length=14), nullable=True),
        sa.Column("numero_asignado", sa.Integer(), nullable=True),
        sa.Column("comprobante_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comprobante_id"], ["comprobantes.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"], ["lotes_comprobantes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "lote_id",
            "comprobante_ref",
            name="uq_lotes_comprobantes_grupos_lote_ref",
        ),
    )
    op.create_index(
        op.f("ix_lotes_comprobantes_grupos_id"),
        "lotes_comprobantes_grupos",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_lotes_comprobantes_grupos_lote_ref",
        "lotes_comprobantes_grupos",
        ["lote_id", "comprobante_ref"],
        unique=False,
    )
    op.create_table(
        "lotes_comprobantes_filas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fila_excel", sa.Integer(), nullable=False),
        sa.Column("comprobante_ref", sa.String(length=100), nullable=False),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("datos_json", sa.JSON(), nullable=True),
        sa.Column("mensajes_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.Column("grupo_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grupo_id"], ["lotes_comprobantes_grupos.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"], ["lotes_comprobantes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lotes_comprobantes_filas_id"),
        "lotes_comprobantes_filas",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_lotes_comprobantes_filas_lote_fila",
        "lotes_comprobantes_filas",
        ["lote_id", "fila_excel"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_lotes_comprobantes_filas_lote_fila", table_name="lotes_comprobantes_filas"
    )
    op.drop_index(
        op.f("ix_lotes_comprobantes_filas_id"), table_name="lotes_comprobantes_filas"
    )
    op.drop_table("lotes_comprobantes_filas")
    op.drop_index(
        "ix_lotes_comprobantes_grupos_lote_ref", table_name="lotes_comprobantes_grupos"
    )
    op.drop_index(
        op.f("ix_lotes_comprobantes_grupos_id"), table_name="lotes_comprobantes_grupos"
    )
    op.drop_table("lotes_comprobantes_grupos")
    op.drop_index(op.f("ix_comprobante_items_id"), table_name="comprobante_items")
    op.drop_table("comprobante_items")
    op.drop_index(op.f("ix_lotes_comprobantes_id"), table_name="lotes_comprobantes")
    op.drop_index("ix_lotes_comprobantes_hash", table_name="lotes_comprobantes")
    op.drop_index(
        "ix_lotes_comprobantes_empresa_estado", table_name="lotes_comprobantes"
    )
    op.drop_table("lotes_comprobantes")
    op.drop_index("ix_comprobantes_tipo_numero", table_name="comprobantes")
    op.drop_index(op.f("ix_comprobantes_id"), table_name="comprobantes")
    op.drop_index("ix_comprobantes_fecha_emision", table_name="comprobantes")
    op.drop_index("ix_comprobantes_estado", table_name="comprobantes")
    op.drop_index("ix_comprobantes_empresa_fecha", table_name="comprobantes")
    op.drop_index("ix_comprobantes_cae", table_name="comprobantes")
    op.drop_table("comprobantes")
    op.drop_index(op.f("ix_usuarios_id"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_puntos_venta_id"), table_name="puntos_venta")
    op.drop_table("puntos_venta")
    op.drop_index("ix_clientes_tipo_numero_doc", table_name="clientes")
    op.drop_index("ix_clientes_razon_social", table_name="clientes")
    op.drop_index(op.f("ix_clientes_id"), table_name="clientes")
    op.drop_index("ix_clientes_empresa_activo", table_name="clientes")
    op.drop_table("clientes")
    op.drop_index(op.f("ix_certificados_id"), table_name="certificados")
    op.drop_table("certificados")
    op.drop_index(op.f("ix_empresas_id"), table_name="empresas")
    op.drop_index(op.f("ix_empresas_cuit"), table_name="empresas")
    op.drop_table("empresas")
    # ### end Alembic commands ###
